documentation_url: https://github.com/NEU-ABLE-LAB/able-workflow-weather-example
homepage_url: https://github.com/NEU-ABLE-LAB/able-workflow-weather-example
organization_name: Northeastern University ABLE Lab
organization_slug: NEU-ABLE-LAB
package_name: able_weather
project_authors:
-   email: mi.kane@northeastern.edu
    name: Michael Kane
project_description: A snakemake workflow with an associated python package containing
    modules for datasets, features, and models for extracting, transforming, and
    loading weather data.
project_name: able-workflow-weather-example
repository_url: https://github.com/NEU-ABLE-LAB/able-workflow-weather-example
